# Generated by Django 4.0.2 on 2022-02-22 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificates',
            old_name='uptadet_at',
            new_name='updated_at',
        ),
    ]
