# Generated by Django 4.0.2 on 2022-02-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='lecture_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
